### ISSUE TITLE
Separation issue

### ISSUE THREAD

**Issue by sevospl** [programmersforum-reborn/discourse-wide-posts#2]
The separation between the end of the topic and the suggested topics is shorter than the separation between the posts.

Screenshosts:
On the top: https://i.imgur.com/ojerRBA.png
On the bottom: https://i.imgur.com/LjgE0oh.png (it's shorter)

I'm a maniac of symmetry and such inconsistency bothers me a little. 😂

**Comment by AlexP11223** [comment]
Yeah, it is a bit more difficult to fix though because of `75%` (used by the original author) which means different things in different contexts. 

I probably will refactor the width calculation to use additional size in px (e.g. `width: calc(#{$topic-body-width} + (#{$topic-body-width-padding} * 2) + 120px);` where the first two values are standard Discourse variables and 120px is the size from settings). It is also needed to adjust the editor window size to make the preview the same size as the post.

**Comment by AlexP11223** [comment]
Fixed.

Also added an option to increase the editor max width to make the preview match the post width. Not perfectly the same width, but the standard one has the same issue.
